/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.Icon;
/**
 *
 * @author Jefry
 */
public class BlackJack211 extends javax.swing.JFrame {
Timer t;
int c1=0,p1=0;
int contadorclicks=5;
int contadorpc=10;
Random rand = new Random();
ImageIcon [] imagenes=new ImageIcon[43];
ImageIcon imagen1=new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"));
Icon imagen2=new javax.swing.ImageIcon(getClass().getResource("/blackjack/loser.gif"));
Icon imagen3=new javax.swing.ImageIcon(getClass().getResource("/blackjack/ganaste.gif"));
int arreglo[] = new int[10];

    /**
     * Creates new form BlackJack21
     */
    public BlackJack211() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        btnnuevojuego = new javax.swing.JButton();
        btnpedircarta = new javax.swing.JButton();
        btnterminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtpc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        carta3humano = new javax.swing.JButton();
        carta2humano = new javax.swing.JButton();
        carta5humano = new javax.swing.JButton();
        carta4humano = new javax.swing.JButton();
        carta1humano = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        carta1pc = new javax.swing.JButton();
        carta2pc = new javax.swing.JButton();
        carta3pc = new javax.swing.JButton();
        carta4pc = new javax.swing.JButton();
        carta5pc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/blackjack_table.png"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);

        btnnuevojuego.setText("NUEVO JUEGO");
        btnnuevojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevojuegoActionPerformed(evt);
            }
        });

        btnpedircarta.setText("PEDIR CARTA");
        btnpedircarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpedircartaMouseClicked(evt);
            }
        });

        btnterminar.setText("TERMINAR");
        btnterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnterminarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel11.setText("PUNTAJE DE USUARIO: ");

        txtusuario.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel13.setText("PUNTAJE PC: ");

        txtpc.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)), "Tu Baraja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Calibri", 3, 18))); // NOI18N
        jPanel2.setOpaque(false);

        carta3humano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta3humano.setContentAreaFilled(false);

        carta2humano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta2humano.setContentAreaFilled(false);

        carta5humano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta5humano.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        carta5humano.setContentAreaFilled(false);

        carta4humano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta4humano.setContentAreaFilled(false);

        carta1humano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta1humano.setContentAreaFilled(false);
        carta1humano.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carta1humano, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta2humano, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta3humano, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta4humano, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta5humano, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carta1humano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta5humano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta4humano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta3humano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta2humano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 204)), "PC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setOpaque(false);

        carta1pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta1pc.setBorderPainted(false);
        carta1pc.setContentAreaFilled(false);
        carta1pc.setFocusPainted(false);

        carta2pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta2pc.setContentAreaFilled(false);

        carta3pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta3pc.setContentAreaFilled(false);

        carta4pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta4pc.setContentAreaFilled(false);

        carta5pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/card.png"))); // NOI18N
        carta5pc.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carta1pc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta2pc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta3pc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta4pc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carta5pc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(carta1pc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta5pc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta4pc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta3pc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta2pc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(335, 335, 335))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(585, 585, 585)))
                        .addGroup(jcMousePanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnnuevojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnterminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnpedircarta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32)
                        .addComponent(txtpc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(632, 632, 632))))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(50, 50, 50)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnnuevojuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnpedircarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnterminar)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenu3.setText("Musica");

        jMenuItem2.setText("Sonido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Silencio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Record");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpedircartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpedircartaMouseClicked
        // TODO add your handling code here:
        if (btnpedircarta.isEnabled()){
        int respuesta= JOptionPane.showConfirmDialog(rootPane, "Estas seguro de pedir una carta",
                "aviso", JOptionPane.YES_NO_CANCEL_OPTION);
        if (respuesta== JOptionPane.YES_OPTION){
        contadorclicks--;
        if (contadorclicks==4){
        carta2humano.setIcon(imagenes[arreglo[1]]);
        if(carta2humano.getIcon().equals(imagenes[0])||carta2humano.getIcon().equals(imagenes[1])||
                carta2humano.getIcon().equals(imagenes[2])||carta2humano.getIcon().equals(imagenes[3])){
            if(c1<11){
            c1+=11;
            txtusuario.setText(""+c1);
            }
            else{
                c1+=1;
                txtusuario.setText(""+c1);
            }
        }
        else if(carta2humano.getIcon().equals(imagenes[4])||carta2humano.getIcon().equals(imagenes[5])||
                carta2humano.getIcon().equals(imagenes[6])||carta2humano.getIcon().equals(imagenes[7])){
            c1+=2;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[8])||carta2humano.getIcon().equals(imagenes[9])||
                carta2humano.getIcon().equals(imagenes[10])||carta2humano.getIcon().equals(imagenes[11])){
            c1+=3;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[12])||carta2humano.getIcon().equals(imagenes[13])||
                carta2humano.getIcon().equals(imagenes[14])||carta2humano.getIcon().equals(imagenes[15])){
            c1+=4;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[16])||carta2humano.getIcon().equals(imagenes[17])||
                carta2humano.getIcon().equals(imagenes[18])||carta2humano.getIcon().equals(imagenes[19])){
            c1+=5;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[20])||carta2humano.getIcon().equals(imagenes[21])||
                carta2humano.getIcon().equals(imagenes[22])||carta2humano.getIcon().equals(imagenes[23])){
            c1+=6;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[24])||carta2humano.getIcon().equals(imagenes[25])||
                carta2humano.getIcon().equals(imagenes[26])||carta2humano.getIcon().equals(imagenes[27])){
            c1+=7;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[28])||carta2humano.getIcon().equals(imagenes[29])||
                carta2humano.getIcon().equals(imagenes[30])||carta2humano.getIcon().equals(imagenes[31])){
            c1+=8;
            txtusuario.setText(""+c1);
        }
        else if(carta2humano.getIcon().equals(imagenes[32])||carta2humano.getIcon().equals(imagenes[33])||
                carta2humano.getIcon().equals(imagenes[34])||carta2humano.getIcon().equals(imagenes[35])){
            c1+=9;
            txtusuario.setText(""+c1);
        }
        else{
            c1+=10;
            txtusuario.setText(""+c1);
        }
        comprobar1();
        }
        else if (contadorclicks==3){
            carta3humano.setIcon(imagenes[arreglo[2]]);
            if(carta3humano.getIcon().equals(imagenes[0])||carta3humano.getIcon().equals(imagenes[1])||
                carta3humano.getIcon().equals(imagenes[2])||carta3humano.getIcon().equals(imagenes[3])){
            if(c1<11){
            c1+=11;
            txtusuario.setText(""+c1);
            }
            else{
                c1+=1;
                txtusuario.setText(""+c1);
            }
        }
        else if(carta3humano.getIcon().equals(imagenes[4])||carta3humano.getIcon().equals(imagenes[5])||
                carta3humano.getIcon().equals(imagenes[6])||carta3humano.getIcon().equals(imagenes[7])){
            c1+=2;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[8])||carta3humano.getIcon().equals(imagenes[9])||
                carta3humano.getIcon().equals(imagenes[10])||carta3humano.getIcon().equals(imagenes[11])){
            c1+=3;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[12])||carta3humano.getIcon().equals(imagenes[13])||
                carta3humano.getIcon().equals(imagenes[14])||carta3humano.getIcon().equals(imagenes[15])){
            c1+=4;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[16])||carta3humano.getIcon().equals(imagenes[17])||
                carta3humano.getIcon().equals(imagenes[18])||carta3humano.getIcon().equals(imagenes[19])){
            c1+=5;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[20])||carta3humano.getIcon().equals(imagenes[21])||
                carta3humano.getIcon().equals(imagenes[22])||carta3humano.getIcon().equals(imagenes[23])){
            c1+=6;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[24])||carta3humano.getIcon().equals(imagenes[25])||
                carta3humano.getIcon().equals(imagenes[26])||carta3humano.getIcon().equals(imagenes[27])){
            c1+=7;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[28])||carta3humano.getIcon().equals(imagenes[29])||
                carta3humano.getIcon().equals(imagenes[30])||carta3humano.getIcon().equals(imagenes[31])){
            c1+=8;
            txtusuario.setText(""+c1);
        }
        else if(carta3humano.getIcon().equals(imagenes[32])||carta3humano.getIcon().equals(imagenes[33])||
                carta3humano.getIcon().equals(imagenes[34])||carta3humano.getIcon().equals(imagenes[35])){
            c1+=9;
            txtusuario.setText(""+c1);
        }
        else{
            c1+=10;
            txtusuario.setText(""+c1);
        }
            comprobar1();
        }   
        else if (contadorclicks==2){
            carta4humano.setIcon(imagenes[arreglo[3]]);
            if(carta4humano.getIcon().equals(imagenes[0])||carta4humano.getIcon().equals(imagenes[1])||
                carta4humano.getIcon().equals(imagenes[2])||carta4humano.getIcon().equals(imagenes[3])){
            if(c1<11){
            c1+=11;
            txtusuario.setText(""+c1);
            }
            else{
                c1+=1;
                txtusuario.setText(""+c1);
            }
        }
        else if(carta4humano.getIcon().equals(imagenes[4])||carta4humano.getIcon().equals(imagenes[5])||
                carta4humano.getIcon().equals(imagenes[6])||carta4humano.getIcon().equals(imagenes[7])){
            c1+=2;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[8])||carta4humano.getIcon().equals(imagenes[9])||
                carta4humano.getIcon().equals(imagenes[10])||carta4humano.getIcon().equals(imagenes[11])){
            c1+=3;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[12])||carta4humano.getIcon().equals(imagenes[13])||
                carta4humano.getIcon().equals(imagenes[14])||carta4humano.getIcon().equals(imagenes[15])){
            c1+=4;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[16])||carta4humano.getIcon().equals(imagenes[17])||
                carta4humano.getIcon().equals(imagenes[18])||carta4humano.getIcon().equals(imagenes[19])){
            c1+=5;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[20])||carta4humano.getIcon().equals(imagenes[21])||
                carta4humano.getIcon().equals(imagenes[22])||carta4humano.getIcon().equals(imagenes[23])){
            c1+=6;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[24])||carta4humano.getIcon().equals(imagenes[25])||
                carta4humano.getIcon().equals(imagenes[26])||carta4humano.getIcon().equals(imagenes[27])){
            c1+=7;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[28])||carta4humano.getIcon().equals(imagenes[29])||
                carta4humano.getIcon().equals(imagenes[30])||carta4humano.getIcon().equals(imagenes[31])){
            c1+=8;
            txtusuario.setText(""+c1);
        }
        else if(carta4humano.getIcon().equals(imagenes[32])||carta4humano.getIcon().equals(imagenes[33])||
                carta4humano.getIcon().equals(imagenes[34])||carta4humano.getIcon().equals(imagenes[35])){
            c1+=9;
            txtusuario.setText(""+c1);
        }
        else{
            c1+=10;
            txtusuario.setText(""+c1);
        }
            comprobar1();
        }
        else if (contadorclicks==1){
            carta5humano.setIcon(imagenes[arreglo[4]]);
        if(carta5humano.getIcon().equals(imagenes[0])||carta5humano.getIcon().equals(imagenes[1])||
                carta5humano.getIcon().equals(imagenes[2])||carta5humano.getIcon().equals(imagenes[3])){
            if(c1<11){
            c1+=11;
            txtusuario.setText(""+c1);
            }
            else{
                c1+=1;
                txtusuario.setText(""+c1);
            }
        }
        else if(carta5humano.getIcon().equals(imagenes[4])||carta5humano.getIcon().equals(imagenes[5])||
                carta5humano.getIcon().equals(imagenes[6])||carta5humano.getIcon().equals(imagenes[7])){
            c1+=2;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[8])||carta5humano.getIcon().equals(imagenes[9])||
                carta5humano.getIcon().equals(imagenes[10])||carta5humano.getIcon().equals(imagenes[11])){
            c1+=3;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[12])||carta5humano.getIcon().equals(imagenes[13])||
                carta5humano.getIcon().equals(imagenes[14])||carta5humano.getIcon().equals(imagenes[15])){
            c1+=4;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[16])||carta5humano.getIcon().equals(imagenes[17])||
                carta5humano.getIcon().equals(imagenes[18])||carta5humano.getIcon().equals(imagenes[19])){
            c1+=5;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[20])||carta5humano.getIcon().equals(imagenes[21])||
                carta5humano.getIcon().equals(imagenes[22])||carta5humano.getIcon().equals(imagenes[23])){
            c1+=6;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[24])||carta5humano.getIcon().equals(imagenes[25])||
                carta5humano.getIcon().equals(imagenes[26])||carta5humano.getIcon().equals(imagenes[27])){
            c1+=7;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[28])||carta5humano.getIcon().equals(imagenes[29])||
                carta5humano.getIcon().equals(imagenes[30])||carta5humano.getIcon().equals(imagenes[31])){
            c1+=8;
            txtusuario.setText(""+c1);
        }
        else if(carta5humano.getIcon().equals(imagenes[32])||carta5humano.getIcon().equals(imagenes[33])||
                carta5humano.getIcon().equals(imagenes[34])||carta5humano.getIcon().equals(imagenes[35])){
            c1+=9;
            txtusuario.setText(""+c1);
        }
        else{
            c1+=10;
            txtusuario.setText(""+c1);
        }
            comprobar1();
        }
        }
        }
    }//GEN-LAST:event_btnpedircartaMouseClicked

    private void btnterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnterminarActionPerformed
        // TODO add your handling code here:
        carta1humano.setEnabled(false);
        carta2humano.setEnabled(false);
        carta3humano.setEnabled(false);
        carta4humano.setEnabled(false);
        carta5humano.setEnabled(false);
        btnpedircarta.setEnabled(false);
        btnterminar.setEnabled(false);
        contadorclicks=0;
        t.start();
    }//GEN-LAST:event_btnterminarActionPerformed

    private void btnnuevojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevojuegoActionPerformed
        // TODO add your handling code here:
        contadorclicks=5;
          int limite = 39;
          int contador = 0;
          do
          {
               int i, n = rand.nextInt(limite + 1);
               for(i = 0; i < contador; i++)
                    if(arreglo[i] == n)
                         break;
               if(i == contador)
                    arreglo [contador++] = n;
          } while(contador < 10);
        imagenes[0]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/1_0.png"));
        imagenes[1]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/1_1.png"));
        imagenes[2]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/1_2.png"));
        imagenes[3]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/1_3.png"));
        imagenes[4]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/2_0.png"));
        imagenes[5]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/2_1.png"));
        imagenes[6]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/2_2.png"));
        imagenes[7]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/2_3.png"));
        imagenes[8]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/3_0.png"));
        imagenes[9]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/3_1.png"));
        imagenes[10]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/3_2.png"));
        imagenes[11]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/3_3.png"));
        imagenes[12]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/4_0.png"));
        imagenes[13]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/4_1.png"));
        imagenes[14]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/4_2.png"));
        imagenes[15]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/4_3.png"));
        imagenes[16]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/5_0.png"));
        imagenes[17]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/5_1.png"));
        imagenes[18]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/5_2.png"));
        imagenes[19]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/5_3.png"));
        imagenes[20]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/6_0.png"));
        imagenes[21]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/6_1.png"));
        imagenes[22]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/6_2.png"));
        imagenes[23]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/6_3.png"));
        imagenes[24]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/7_0.png"));
        imagenes[25]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/7_1.png"));
        imagenes[26]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/7_2.png"));
        imagenes[27]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/7_3.png"));
        imagenes[28]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/8_0.png"));
        imagenes[29]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/8_1.png"));
        imagenes[30]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/8_2.png"));
        imagenes[31]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/8_3.png"));
        imagenes[32]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/9_0.png"));
        imagenes[33]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/9_1.png"));
        imagenes[34]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/9_2.png"));
        imagenes[35]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/9_3.png"));
        imagenes[36]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/10_0.png"));
        imagenes[37]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/10_1.png"));
        imagenes[38]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/10_2.png"));
        imagenes[39]=new javax.swing.ImageIcon(getClass().getResource("/blackjack/10_3.png"));
        
        txtusuario.setText("");
        txtpc.setText("");
        c1=0;
        p1=0;
        carta2humano.setIcon(imagen1);
        carta3humano.setIcon(imagen1);
        carta4humano.setIcon(imagen1);
        carta5humano.setIcon(imagen1);
        carta1humano.setEnabled(true);
        carta2humano.setEnabled(true);
        carta3humano.setEnabled(true);
        carta4humano.setEnabled(true);
        carta5humano.setEnabled(true);
        btnterminar.setEnabled(true);
        btnpedircarta.setEnabled(true);
        contadorclicks=5;
        carta1pc.setIcon(imagen1);
        carta2pc.setIcon(imagen1);
        carta3pc.setIcon(imagen1);
        carta4pc.setIcon(imagen1);
        carta5pc.setIcon(imagen1);
        
        carta1humano.setIcon(imagenes[arreglo[0]]);
        if(carta1humano.getIcon().equals(imagenes[0])||carta1humano.getIcon().equals(imagenes[1])||
                carta1humano.getIcon().equals(imagenes[2])||carta1humano.getIcon().equals(imagenes[3])){
            if(c1<11){
            c1+=11;
            txtusuario.setText(""+c1);
            }
            else{
                c1+=1;
                txtusuario.setText(""+c1);
            }
        }
        else if(carta1humano.getIcon().equals(imagenes[4])||carta1humano.getIcon().equals(imagenes[5])||
                carta1humano.getIcon().equals(imagenes[6])||carta1humano.getIcon().equals(imagenes[7])){
            c1+=2;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[8])||carta1humano.getIcon().equals(imagenes[9])||
                carta1humano.getIcon().equals(imagenes[10])||carta1humano.getIcon().equals(imagenes[11])){
            c1+=3;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[12])||carta1humano.getIcon().equals(imagenes[13])||
                carta1humano.getIcon().equals(imagenes[14])||carta1humano.getIcon().equals(imagenes[15])){
            c1+=4;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[16])||carta1humano.getIcon().equals(imagenes[17])||
                carta1humano.getIcon().equals(imagenes[18])||carta1humano.getIcon().equals(imagenes[19])){
            c1+=5;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[20])||carta1humano.getIcon().equals(imagenes[21])||
                carta1humano.getIcon().equals(imagenes[22])||carta1humano.getIcon().equals(imagenes[23])){
            c1+=6;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[24])||carta1humano.getIcon().equals(imagenes[25])||
                carta1humano.getIcon().equals(imagenes[26])||carta1humano.getIcon().equals(imagenes[27])){
            c1+=7;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[28])||carta1humano.getIcon().equals(imagenes[29])||
                carta1humano.getIcon().equals(imagenes[30])||carta1humano.getIcon().equals(imagenes[31])){
            c1+=8;
            txtusuario.setText(""+c1);
        }
        else if(carta1humano.getIcon().equals(imagenes[32])||carta1humano.getIcon().equals(imagenes[33])||
                carta1humano.getIcon().equals(imagenes[34])||carta1humano.getIcon().equals(imagenes[35])){
            c1+=9;
            txtusuario.setText(""+c1);
        }
        else{
            c1+=10;
            txtusuario.setText(""+c1);
        }
    }//GEN-LAST:event_btnnuevojuegoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        t=new Timer(1000, new Accion());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/blackjack/Die_Antwoord_-_I_Fink_U_Freeky_Lyrics_On_Screen_.wav"));
        sonido.play();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/blackjack/Die_Antwoord_-_I_Fink_U_Freeky_Lyrics_On_Screen_.wav"));
        sonido.stop();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Record().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJack211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJack211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJack211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJack211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJack211().setVisible(true);
                 AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/blackjack/Die_Antwoord_-_I_Fink_U_Freeky_Lyrics_On_Screen_.wav"));
        sonido.play();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnuevojuego;
    private javax.swing.JButton btnpedircarta;
    private javax.swing.JButton btnterminar;
    private javax.swing.JButton carta1humano;
    private javax.swing.JButton carta1pc;
    private javax.swing.JButton carta2humano;
    private javax.swing.JButton carta2pc;
    private javax.swing.JButton carta3humano;
    private javax.swing.JButton carta3pc;
    private javax.swing.JButton carta4humano;
    private javax.swing.JButton carta4pc;
    private javax.swing.JButton carta5humano;
    private javax.swing.JButton carta5pc;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTextField txtpc;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
public class Accion implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            contadorpc--;
            if (contadorpc==8){
                carta1pc.setIcon(imagenes[arreglo[5]]);
                if(carta1pc.getIcon().equals(imagenes[0])||carta1pc.getIcon().equals(imagenes[1])||
                carta1pc.getIcon().equals(imagenes[2])||carta1pc.getIcon().equals(imagenes[3])){
            if(p1<11){
            p1+=11;
            txtpc.setText(""+p1);
            }
            else{
                p1+=1;
                txtpc.setText(""+p1);
            }
        }
        else if(carta1pc.getIcon().equals(imagenes[4])||carta1pc.getIcon().equals(imagenes[5])||
                carta1pc.getIcon().equals(imagenes[6])||carta1pc.getIcon().equals(imagenes[7])){
            p1+=2;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[8])||carta1pc.getIcon().equals(imagenes[9])||
                carta1pc.getIcon().equals(imagenes[10])||carta1pc.getIcon().equals(imagenes[11])){
            p1+=3;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[12])||carta1pc.getIcon().equals(imagenes[13])||
                carta1pc.getIcon().equals(imagenes[14])||carta1pc.getIcon().equals(imagenes[15])){
            p1+=4;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[16])||carta1pc.getIcon().equals(imagenes[17])||
                carta1pc.getIcon().equals(imagenes[18])||carta1pc.getIcon().equals(imagenes[19])){
            p1+=5;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[20])||carta1pc.getIcon().equals(imagenes[21])||
                carta1pc.getIcon().equals(imagenes[22])||carta1pc.getIcon().equals(imagenes[23])){
            p1+=6;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[24])||carta1pc.getIcon().equals(imagenes[25])||
                carta1pc.getIcon().equals(imagenes[26])||carta1pc.getIcon().equals(imagenes[27])){
            p1+=7;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[28])||carta1pc.getIcon().equals(imagenes[29])||
                carta1pc.getIcon().equals(imagenes[30])||carta1pc.getIcon().equals(imagenes[31])){
            p1+=8;
            txtpc.setText(""+p1);
        }
        else if(carta1pc.getIcon().equals(imagenes[32])||carta1pc.getIcon().equals(imagenes[33])||
                carta1pc.getIcon().equals(imagenes[34])||carta1pc.getIcon().equals(imagenes[35])){
            p1+=9;
            txtpc.setText(""+p1);
        }
        else{
            p1+=10;
            txtpc.setText(""+p1);
        }
                comprobar2();
            }
            else if (contadorpc==6){
                carta2pc.setIcon(imagenes[arreglo[6]]);
                if(carta2pc.getIcon().equals(imagenes[0])||carta2pc.getIcon().equals(imagenes[1])||
                carta2pc.getIcon().equals(imagenes[2])||carta2pc.getIcon().equals(imagenes[3])){
            if(p1<11){
            p1+=11;
            txtpc.setText(""+p1);
            }
            else{
                p1+=1;
                txtpc.setText(""+p1);
            }
        }
        else if(carta2pc.getIcon().equals(imagenes[4])||carta2pc.getIcon().equals(imagenes[5])||
                carta2pc.getIcon().equals(imagenes[6])||carta2pc.getIcon().equals(imagenes[7])){
            p1+=2;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[8])||carta2pc.getIcon().equals(imagenes[9])||
                carta2pc.getIcon().equals(imagenes[10])||carta2pc.getIcon().equals(imagenes[11])){
            p1+=3;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[12])||carta2pc.getIcon().equals(imagenes[13])||
                carta2pc.getIcon().equals(imagenes[14])||carta2pc.getIcon().equals(imagenes[15])){
            p1+=4;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[16])||carta2pc.getIcon().equals(imagenes[17])||
                carta2pc.getIcon().equals(imagenes[18])||carta2pc.getIcon().equals(imagenes[19])){
            p1+=5;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[20])||carta2pc.getIcon().equals(imagenes[21])||
                carta2pc.getIcon().equals(imagenes[22])||carta2pc.getIcon().equals(imagenes[23])){
            p1+=6;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[24])||carta2pc.getIcon().equals(imagenes[25])||
                carta2pc.getIcon().equals(imagenes[26])||carta2pc.getIcon().equals(imagenes[27])){
            p1+=7;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[28])||carta2pc.getIcon().equals(imagenes[29])||
                carta2pc.getIcon().equals(imagenes[30])||carta2pc.getIcon().equals(imagenes[31])){
            p1+=8;
            txtpc.setText(""+p1);
        }
        else if(carta2pc.getIcon().equals(imagenes[32])||carta2pc.getIcon().equals(imagenes[33])||
                carta2pc.getIcon().equals(imagenes[34])||carta2pc.getIcon().equals(imagenes[35])){
            p1+=9;
            txtpc.setText(""+p1);
        }
        else{
            p1+=10;
            txtpc.setText(""+p1);
        }
        comprobar2();
        }
            else if (contadorpc==4){
                carta3pc.setIcon(imagenes[arreglo[7]]);
                         if(carta3pc.getIcon().equals(imagenes[0])||carta3pc.getIcon().equals(imagenes[1])||
                carta3pc.getIcon().equals(imagenes[2])||carta3pc.getIcon().equals(imagenes[3])){
            if(p1<11){
            p1+=11;
            txtpc.setText(""+p1);
            }
            else{
                p1+=1;
                txtpc.setText(""+p1);
            }
        }
        else if(carta3pc.getIcon().equals(imagenes[4])||carta3pc.getIcon().equals(imagenes[5])||
                carta3pc.getIcon().equals(imagenes[6])||carta3pc.getIcon().equals(imagenes[7])){
            p1+=2;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[8])||carta3pc.getIcon().equals(imagenes[9])||
                carta3pc.getIcon().equals(imagenes[10])||carta3pc.getIcon().equals(imagenes[11])){
            p1+=3;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[12])||carta3pc.getIcon().equals(imagenes[13])||
                carta3pc.getIcon().equals(imagenes[14])||carta3pc.getIcon().equals(imagenes[15])){
            p1+=4;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[16])||carta3pc.getIcon().equals(imagenes[17])||
                carta3pc.getIcon().equals(imagenes[18])||carta3pc.getIcon().equals(imagenes[19])){
            p1+=5;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[20])||carta3pc.getIcon().equals(imagenes[21])||
                carta3pc.getIcon().equals(imagenes[22])||carta3pc.getIcon().equals(imagenes[23])){
            p1+=6;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[24])||carta3pc.getIcon().equals(imagenes[25])||
                carta3pc.getIcon().equals(imagenes[26])||carta3pc.getIcon().equals(imagenes[27])){
            p1+=7;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[28])||carta3pc.getIcon().equals(imagenes[29])||
                carta3pc.getIcon().equals(imagenes[30])||carta3pc.getIcon().equals(imagenes[31])){
            p1+=8;
            txtpc.setText(""+p1);
        }
        else if(carta3pc.getIcon().equals(imagenes[32])||carta3pc.getIcon().equals(imagenes[33])||
                carta3pc.getIcon().equals(imagenes[34])||carta3pc.getIcon().equals(imagenes[35])){
            p1+=9;
            txtpc.setText(""+p1);
        }
        else{
            p1+=10;
            txtpc.setText(""+p1);
        }
        comprobar2();
            }
            else if (contadorpc==2){
                carta4pc.setIcon(imagenes[arreglo[8]]);
             if(carta4pc.getIcon().equals(imagenes[0])||carta4pc.getIcon().equals(imagenes[1])||
                carta4pc.getIcon().equals(imagenes[2])||carta4pc.getIcon().equals(imagenes[3])){
            if(p1<11){
            p1+=11;
            txtpc.setText(""+p1);
            }
            else{
                p1+=1;
                txtpc.setText(""+p1);
            }
        }
        else if(carta4pc.getIcon().equals(imagenes[4])||carta4pc.getIcon().equals(imagenes[5])||
                carta4pc.getIcon().equals(imagenes[6])||carta4pc.getIcon().equals(imagenes[7])){
            p1+=2;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[8])||carta4pc.getIcon().equals(imagenes[9])||
                carta4pc.getIcon().equals(imagenes[10])||carta4pc.getIcon().equals(imagenes[11])){
            p1+=3;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[12])||carta4pc.getIcon().equals(imagenes[13])||
                carta4pc.getIcon().equals(imagenes[14])||carta4pc.getIcon().equals(imagenes[15])){
            p1+=4;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[16])||carta4pc.getIcon().equals(imagenes[17])||
                carta4pc.getIcon().equals(imagenes[18])||carta4pc.getIcon().equals(imagenes[19])){
            p1+=5;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[20])||carta4pc.getIcon().equals(imagenes[21])||
                carta4pc.getIcon().equals(imagenes[22])||carta4pc.getIcon().equals(imagenes[23])){
            p1+=6;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[24])||carta4pc.getIcon().equals(imagenes[25])||
                carta4pc.getIcon().equals(imagenes[26])||carta4pc.getIcon().equals(imagenes[27])){
            p1+=7;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[28])||carta4pc.getIcon().equals(imagenes[29])||
                carta4pc.getIcon().equals(imagenes[30])||carta4pc.getIcon().equals(imagenes[31])){
            p1+=8;
            txtpc.setText(""+p1);
        }
        else if(carta4pc.getIcon().equals(imagenes[32])||carta4pc.getIcon().equals(imagenes[33])||
                carta4pc.getIcon().equals(imagenes[34])||carta4pc.getIcon().equals(imagenes[35])){
            p1+=9;
            txtpc.setText(""+p1);
        }
        else{
            p1+=10;
            txtpc.setText(""+p1);
        }
        comprobar2();
            }
            else if (contadorpc==0){
                carta5pc.setIcon(imagenes[arreglo[9]]);
             if(carta5pc.getIcon().equals(imagenes[0])||carta5pc.getIcon().equals(imagenes[1])||
                carta5pc.getIcon().equals(imagenes[2])||carta5pc.getIcon().equals(imagenes[3])){
            if(p1<11){
            p1+=11;
            txtpc.setText(""+p1);
            }
            else{
                p1+=1;
                txtpc.setText(""+p1);
            }
        }
        else if(carta5pc.getIcon().equals(imagenes[4])||carta5pc.getIcon().equals(imagenes[5])||
                carta5pc.getIcon().equals(imagenes[6])||carta5pc.getIcon().equals(imagenes[7])){
            p1+=2;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[8])||carta5pc.getIcon().equals(imagenes[9])||
                carta5pc.getIcon().equals(imagenes[10])||carta5pc.getIcon().equals(imagenes[11])){
            p1+=3;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[12])||carta5pc.getIcon().equals(imagenes[13])||
                carta5pc.getIcon().equals(imagenes[14])||carta5pc.getIcon().equals(imagenes[15])){
            p1+=4;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[16])||carta5pc.getIcon().equals(imagenes[17])||
                carta5pc.getIcon().equals(imagenes[18])||carta5pc.getIcon().equals(imagenes[19])){
            p1+=5;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[20])||carta5pc.getIcon().equals(imagenes[21])||
                carta5pc.getIcon().equals(imagenes[22])||carta5pc.getIcon().equals(imagenes[23])){
            p1+=6;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[24])||carta5pc.getIcon().equals(imagenes[25])||
                carta5pc.getIcon().equals(imagenes[26])||carta5pc.getIcon().equals(imagenes[27])){
            p1+=7;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[28])||carta5pc.getIcon().equals(imagenes[29])||
                carta5pc.getIcon().equals(imagenes[30])||carta5pc.getIcon().equals(imagenes[31])){
            p1+=8;
            txtpc.setText(""+p1);
        }
        else if(carta5pc.getIcon().equals(imagenes[32])||carta5pc.getIcon().equals(imagenes[33])||
                carta5pc.getIcon().equals(imagenes[34])||carta5pc.getIcon().equals(imagenes[35])){
            p1+=9;
            txtpc.setText(""+p1);
        }
        else{
            p1+=10;
            txtpc.setText(""+p1);
        }
        comprobar2();
            }
            }
        }
public void comprobar1(){
    if (c1==21){
        JOptionPane.showMessageDialog(rootPane, "Juego hecho por:\nJefry sanchez\n", "Ganaste :D",
                JOptionPane.PLAIN_MESSAGE, imagen3);
        btnterminar.setEnabled(false);
        btnpedircarta.setEnabled(false);
    }
    else if (c1>21){
        JOptionPane.showMessageDialog(rootPane, "Juego hecho por:\nJefry sanchez\n", "Gano la PC T_T",
                JOptionPane.PLAIN_MESSAGE, imagen2);
    btnpedircarta.setEnabled(false);
    btnterminar.setEnabled(false);
}
}
public void comprobar2(){
    if (p1==21 || (p1>c1 && p1<21)){
        JOptionPane.showMessageDialog(rootPane, "Juego hecho por:\nJefry sanchez\n", "Gano la PC T_T",
                JOptionPane.PLAIN_MESSAGE, imagen2);
        t.stop();
        contadorpc=10;
    }
    else if (p1>21 ||(contadorpc==0 && p1<c1) ){
        JOptionPane.showMessageDialog(rootPane, "Juego hecho por:\nJefry sanchez", "Ganaste :D",
                JOptionPane.PLAIN_MESSAGE, imagen3);
    btnpedircarta.setEnabled(false);
    btnterminar.setEnabled(false);
    t.stop();
    contadorpc=10;
    }
}
}
